baseURL = "https://www.joeldare.com/blog"
languageCode = "en-us"
title = "Joel Dare"
author = "Joel Dare"
theme = "hugo-joeldare-theme"
publishDir = "docs"
googleAnalytics = "UA-6888208-1"

[params]
  sitename = "Joel Dare"

[[menu.main]]
    name = "Email"
    url  = "mailto:joel@joeldare.com"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/codazoda"
[[menu.main]]
    name = "Wiki"
    url  = "https://www.joeldare.com/wiki"
