baseURL = "http://blog.joeldare.com/"
languageCode = "en-us"
title = "Joel Dare"
author = "Joel Dare"
theme = "hugo-joeldare"
publishDir = "docs"

[params]
  sitename = "Joel Dare"

[[menu.main]]
    name = "Email"
    url  = "mailto:joel@joeldare.com"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/codazoda"
[[menu.main]]
    name = "Wiki"
    url  = "http://www.joeldare.com/wiki"